//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int id { get; set; }
        public string carName { get; set; }
        public string pickupLocation { get; set; }
        public string pickupTime { get; set; }
        public string dropLocation { get; set; }
        public string dropTime { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
