//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    
    public partial class GetCars_Result1
    {
        public int id { get; set; }
        public string carName { get; set; }
        public Nullable<bool> isBooked { get; set; }
    }
}
